name: Build SDWebImage MAUI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest

    env:
      SDK: 17.5
      NATIVE_RELEASE: 5.21.0
      SRC_FOLDER: SDWebImage-5.21.0
      PROJ_NAME: SDWebImage.xcodeproj

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4


    - name: Download and extract SDWebImage
      run: |
        curl -L https://github.com/SDWebImage/SDWebImage/archive/refs/tags/${{ env.NATIVE_RELEASE }}.zip -o sdwebimage.zip
        unzip sdwebimage.zip
        rm sdwebimage.zip
        
    - name: Modifier le project.pbxproj pour inclure SDCallbackQueue.m dans la cible statique
      working-directory: ${{ env.SRC_FOLDER }} # Adaptez le chemin
      run: |
        PBXPROJ_FILE="${{ env.PROJ_NAME }}/project.pbxproj"
        SOURCES_PHASE_ID="53761308155AD0D5005750A4" # ID de PBXSourcesBuildPhase pour "SDWebImage static"
        BUILD_FILE_ID="321117AA296573680001FC2C"    # ID du PBXBuildFile pour SDCallbackQueue.m
        COMMENT="/* SDCallbackQueue.m in Sources */"
        LINE_TO_ADD="\t\t\t\t${BUILD_FILE_ID} ${COMMENT},"

        # Vérifier si le fichier existe
        if [ ! -f "$PBXPROJ_FILE" ]; then
          echo "Erreur: Fichier $PBXPROJ_FILE non trouvé!"
          exit 1
        fi

        # Vérifier si la ligne est déjà présente dans la bonne section
        # awk est plus adapté pour vérifier DANS la section que grep seul
        already_present=$(awk -v phase_id="$SOURCES_PHASE_ID" -v build_id="$BUILD_FILE_ID" '
          BEGIN { found=0; in_phase=0 }
          $0 ~ phase_id { in_phase=1 }
          in_phase && $0 ~ build_id { found=1; exit }
          in_phase && /};/ { in_phase=0 } # Fin de la section de la phase
          END { print found }
        ' "$PBXPROJ_FILE")

        if [ "$already_present" -eq 1 ]; then
          echo "La référence à ${BUILD_FILE_ID} est déjà présente dans la phase ${SOURCES_PHASE_ID}. Aucune modification nécessaire."
        else
          echo "Ajout de la référence ${BUILD_FILE_ID} à la phase ${SOURCES_PHASE_ID}..."
          # Utilise awk pour insérer la ligne avant le ');' final de la liste 'files'
          # dans la section de la phase de compilation concernée.
          awk -v phase_id="$SOURCES_PHASE_ID" -v line_to_add="$LINE_TO_ADD" '
          BEGIN { in_phase=0; in_files=0 }
          $0 ~ phase_id { in_phase=1 } # Trouvé le début de la section de la phase
          in_phase && /files = \(/ { in_files=1 } # Trouvé le début de la liste files
          in_phase && in_files && /^\s*\);/ { # Trouvé la fin de la liste files DANS la bonne phase
            print line_to_add; # Imprimer la nouvelle ligne AVANT la ligne de fermeture
            in_files=0; # On a fini avec la liste files
          }
          { print } # Imprimer la ligne actuelle
          in_phase && /};/ { in_phase=0 } # Fin de la section de la phase
          ' "$PBXPROJ_FILE" > temp_pbxproj && mv temp_pbxproj "$PBXPROJ_FILE"

          echo "Modification effectuée."
          # Optionnel: Vérifier que l'ajout a bien eu lieu
          grep "$BUILD_FILE_ID" "$PBXPROJ_FILE" || (echo "Erreur: Echec de la vérification de l'ajout"; exit 1)

        fi        
        
        
    - name: Upload .cxcprok files as artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: native-libs
        compression-level: '0'
        path:
          ${{ env.PROJ_NAME }}/project.pbxproj
    
    
    - name: Build SDWebImage for simulator
      run: |
        xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
          -target "SDWebImage static" \
          -sdk iphonesimulator${{ env.SDK }} \
          IPHONEOS_DEPLOYMENT_TARGET=12.2 \
          EXCLUDED_ARCHS="arm64"

    - name: Build SDWebImage for device
      run: |
        xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
          -configuration Release \
          -target "SDWebImage static" \
          -sdk iphoneos${{ env.SDK }} \
          IPHONEOS_DEPLOYMENT_TARGET=12.2
        
#    - name: Build SDWebImage for xcproj
#      run: |
#        xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
#          -configuration Release \
#          -target "SDWebImage XCFramework" \
#          -sdk iphoneos${{ env.SDK }} \
#          IPHONEOS_DEPLOYMENT_TARGET=12.2
#        
#        
#    - name: Upload .a files as artifact
#      uses: actions/upload-artifact@v4.6.2
#      with:
#        name: native-libs
#        compression-level: '0'
#        path:
#          ${{ env.SRC_FOLDER }}/build/**
      
      
      #    - name: Create universal lib with lipo
#      run: |
#        lipo -create \
#          ${{ env.SRC_FOLDER }}/build/Release-iphoneos/libSDWebImage.a \
#          ${{ env.SRC_FOLDER }}/build/Release-iphonesimulator/libSDWebImage.a \
#          -output ./libSDWebImage.a
#        lipo -info ./libSDWebImage.a

    - name: Install .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x' 

    - name: restore workload
      run: dotnet workload restore

    - name: Build .NET binding project
      run: dotnet build -c Release SDWebImage-dotnet.csproj

    - name: Pack NuGet
      run: dotnet pack -c Release SDWebImage-dotnet.csproj

    - name: Upload .nupkg as artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: nuget-package
        compression-level: '0'
        path:
          /Users/runner/work/SDWebImage-dotnet/SDWebImage-dotnet/bin/Release/*.nupkg  

    - name: Upload .a files as artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: native-libs
        compression-level: '0'
        path:
          ${{ env.SRC_FOLDER }}/build/Release-iphoneos/** 
