name: Build SDWebImage MAUI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest

    env:
      SDK: 17.5
      NATIVE_RELEASE: 5.21.0
      SRC_FOLDER: SDWebImage-5.21.0
      PROJ_NAME: SDWebImage.xcodeproj

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4


    - name: Download and extract SDWebImage
      run: |
        curl -L https://github.com/SDWebImage/SDWebImage/archive/refs/tags/${{ env.NATIVE_RELEASE }}.zip -o sdwebimage.zip
        unzip sdwebimage.zip
        rm sdwebimage.zip
        
    - name: Modifier le project.pbxproj pour inclure SDCallbackQueue.m dans la cible statique
      working-directory: ${{ env.SRC_FOLDER }}
      run: |
        PBXPROJ_FILE="${{ env.PROJ_NAME }}/project.pbxproj"
        SOURCES_PHASE_ID="53761308155AD0D5005750A4"
        BUILD_FILE_ID="321117AA296573680001FC2C"
        COMMENT="/* SDCallbackQueue.m in Sources */"
        LINE_TO_ADD="\t\t\t\t${BUILD_FILE_ID} ${COMMENT},"
    
        if [ ! -f "$PBXPROJ_FILE" ]; then
        echo "Erreur: Fichier $PBXPROJ_FILE non trouvé!"
        exit 1
        fi
    
        # Meilleure vérification: rechercher BUILD_FILE_ID dans la section Sources spécifique
        SECTION_CONTENT=$(sed -n "/$SOURCES_PHASE_ID/,/\/* End PBXSourcesBuildPhase \*\//p" "$PBXPROJ_FILE")
        if echo "$SECTION_CONTENT" | grep -q "$BUILD_FILE_ID"; then
        echo "La ligne avec BUILD_FILE_ID $BUILD_FILE_ID existe déjà dans la section Sources avec ID $SOURCES_PHASE_ID"
        echo "Contexte de la ligne existante:"
        grep -n -A 5 -B 5 "$BUILD_FILE_ID" "$PBXPROJ_FILE"
        exit 0
        fi
    
        echo "La ligne n'existe pas dans la section Sources. Ajout en cours..."
    
        # Trouver l'endroit exact où insérer la ligne: juste avant la fermeture de la liste des fichiers
        awk -v phase_id="$SOURCES_PHASE_ID" -v line_to_add="$LINE_TO_ADD" '
        BEGIN { in_phase=0; in_files=0; added=0 }
        # Reconnaître le début de la section Sources avec l'ID
        $0 ~ phase_id " \\/\\* Sources \\*\\/ = {" || $0 ~ phase_id {
        in_phase=1;
        print;
        next;
        }
        # Reconnaître le début de la liste des fichiers
        in_phase && /files = \(/ {
        in_files=1;
        print;
        next;
        }
        # Trouver la fin de la liste des fichiers pour ajouter notre ligne
        in_phase && in_files && /^\s*\);/ {
        if (!added) {
         # Ajouter la ligne juste avant la fermeture de la liste
         print line_to_add;
         added=1;
        }
        print;
        in_files=0;
        next;
        }
        # Fin de la section
        in_phase && /};/ {
        in_phase=0;
        print;
        next;
        }
        # Imprimer toutes les autres lignes inchangées
        { print }
        END {
        if (!added) {
         print "AVERTISSEMENT: Structure attendue non trouvée, la ligne n\'a pas été ajoutée" > "/dev/stderr";
         exit 1;
        }
        }
        ' "$PBXPROJ_FILE" > temp_pbxproj
    
        if [ $? -eq 0 ]; then
        # Vérifier que la ligne a bien été ajoutée dans le fichier temporaire
        if grep -q "$BUILD_FILE_ID" temp_pbxproj; then
         mv temp_pbxproj "$PBXPROJ_FILE"
         echo "Fichier modifié avec succès. Ligne ajoutée dans la section Sources."
        
         # Contexte autour de la ligne ajoutée
         echo "Contexte de la ligne ajoutée (10 lignes autour):"
         grep -n -A 5 -B 5 "$BUILD_FILE_ID" "$PBXPROJ_FILE"
        else
         echo "ERREUR: La ligne n'a pas été ajoutée dans le fichier temporaire."
         rm -f temp_pbxproj
         exit 1
        fi
        else
        echo "ERREUR lors de la modification du fichier."
        rm -f temp_pbxproj
        exit 1
        fi
        
    - name: Upload .cxcproj files as artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: native-libs
        compression-level: '0'
        path:
          ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }}/**
    
    
    - name: Build SDWebImage for simulator
      run: |
        xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
          -target "SDWebImage static" \
          -sdk iphonesimulator${{ env.SDK }} \
          IPHONEOS_DEPLOYMENT_TARGET=12.2 \
          EXCLUDED_ARCHS="arm64"

    - name: Build SDWebImage for device
      run: |
        xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
          -configuration Release \
          -target "SDWebImage static" \
          -sdk iphoneos${{ env.SDK }} \
          IPHONEOS_DEPLOYMENT_TARGET=12.2
        
#    - name: Build SDWebImage for xcproj
#      run: |
#        xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
#          -configuration Release \
#          -target "SDWebImage XCFramework" \
#          -sdk iphoneos${{ env.SDK }} \
#          IPHONEOS_DEPLOYMENT_TARGET=12.2
#        
#        
#    - name: Upload .a files as artifact
#      uses: actions/upload-artifact@v4.6.2
#      with:
#        name: native-libs
#        compression-level: '0'
#        path:
#          ${{ env.SRC_FOLDER }}/build/**
      
      
    - name: Create universal lib with lipo
      run: |
        lipo -create \
          ${{ env.SRC_FOLDER }}/build/Release-iphoneos/libSDWebImage.a \
          ${{ env.SRC_FOLDER }}/build/Release-iphonesimulator/libSDWebImage.a \
          -output ./libSDWebImage.a
        lipo -info ./libSDWebImage.a

    - name: Install .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x' 

    - name: restore workload
      run: dotnet workload restore

    - name: Build .NET binding project
      run: dotnet build -c Release SDWebImage-dotnet.csproj

    - name: Pack NuGet
      run: dotnet pack -c Release SDWebImage-dotnet.csproj

    - name: Upload .nupkg as artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: nuget-package
        compression-level: '0'
        path:
          /Users/runner/work/SDWebImage-dotnet/SDWebImage-dotnet/bin/Release/*.nupkg  

    - name: Upload .a files as artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: native-libs
        compression-level: '0'
        path:
          ${{ env.SRC_FOLDER }}/build/Release-iphoneos/** 
